### ISSUE TITLE
Possible issue: sample_id as int vs str

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cohorts#1]
Sometimes I see integer sorting and sometimes I see alphanumeric sorting; at the least, we should be sure that IDs always match up correctly (i.e. the right sample ID with the right BAM IDs).

**Comment by arahuja** [comment]
I would support forcing the IDs to be strings on load in. Mostly because they may be 0-padded and if we interpret them as int they could lose their meaning. For example `00012`
