### ISSUE TITLE
Statistical significance * on mann whitney and fisher's exact plot 

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cohorts#109]

**Comment by tavinathanson** [comment]
I'm actually unclear whether we want a star, a line, or both?

By line I mean:

![image](https://cloud.githubusercontent.com/assets/322932/17532722/f2fd45c0-5e4f-11e6-8ed7-1e33a51b2f5c.png)

**Comment by tavinathanson** [comment]
Fixed by #112
