### ISSUE TITLE
Show plots in README's usage examples

### ISSUE THREAD

**Issue by iskandr** [hammerlab/cohorts#141]
I think the intent of the library would be a little clearer if the usage examples included the generated plots.

**Comment by tavinathanson** [comment]
Agreed! In general, the README could use an overhaul; was slapped together in a minute and doesn't show off much of the library. Thankfully @jburos is on the case!

**Comment by jburos** [comment]
Agreed. We should probably link to the quick-start from the readme, and/or
migrate done of that content over.

**Comment by jburos** [comment]
I added some plots from the quick-start - closing this for now.
