### ISSUE TITLE
Harmonize with epidisco

### ISSUE THREAD

**Issue by hammer** [hammerlab/cohorts#162]
Cohorts and Epidisco share some functionality. It would be nice to centralize the discussion of how we'll ensure they generate consistent results and ultimately separate concerns.

Currently my biggest concern is that Epidisco uses vaxrank but cohorts uses topiary. https://github.com/hammerlab/vaxrank/issues/31 might solve this issue.

**Comment by tavinathanson** [comment]
Is this a dup. of https://github.com/hammerlab/cohorts/issues/154?

**Comment by tavinathanson** [comment]
It is indeed a dup, closing.
