### ISSUE TITLE
Using only Strelka tier 1 results in divide by zero sometimes

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cohorts#166]
@jburos:

> any idea why I'd see a variant with no ref/alt reads at all? Getting a divide by zero error in vaf calc :confused:
```(Pdb) variant
Variant(contig='13', start=111589766, ref='C', alt='T', reference_name='GRCh37')
(Pdb) sample_info
OrderedDict([('AU', [0, 0]), ('CU', [0, 0]), ('DP', 10), ('FDP', 0), ('GU', [10, 48]), ('SDP', 0), ('SUBDP', 0), ('TU', [0, 1])])
(Pdb) ref_depth
0
(Pdb) int(sample_info[variant.alt+"U"][0])
0
```

From @tavinathanson:

> maybe it is what i thought @ihodes was saying, namely a bug in cohorts since we only grab tier 1, which can sometimes result in 0; so maybe we should filter those out (still weird to me that we didn't hit this before is the thing)

From @jburos:

> was thinking to return depth of 0 & set the vaf to 0 for now; users can/should filter them through qc filters (we could mod the no_filter filter to remove them)

From @tavinathanson:
> i actually don't think `no_filter` should ever do anything, arun was a strong proponent of eventually getting rid of it which i support; added it in for a few reasons though so it's extraction would need to be thoughtful

From @jburos:
>right now the load_variant functions don't do any filtering, which is (i think) expected behavior. so for now i'll leave this & not filter on loading variant_stats .. best practice should be for users to set their own qc filters

From @tavinathanson:
>maybe return depth of 0 and VAF of `None`? 0 for VAF seems wrongish; agree that filters can take it from there

From @jburos:
> sounds good - was thinking `None` as well but didn't know how many things this might break

**Comment by jburos** [comment]
Also related to PR #169
