### ISSUE TITLE
TypeError: "load_maf() got an unexpected keyword argument 'encoding'"

### ISSUE THREAD

**Issue by jburos** [hammerlab/cohorts#203]
Getting a `TypeError` when using a cohort with mafs on python 2.7:

Here is the traceback:
```py
/home/jacquelineburos/miniconda3/envs/xx2/lib/python2.7/site-packages/cohorts/cohort.pyc in _load_single_patient_variants(self, patient, filter_fn, use_cache, **kwargs)
    590         ## get merged variants
    591         logger.debug("... getting merged variants for: {}".format(patient.id))
--> 592         merged_variants = self._load_single_patient_merged_variants(patient, use_cache=use_cache)
    593 
    594         # Note None here is different from 0. We want to preserve None

/home/jacquelineburos/miniconda3/envs/xx2/lib/python2.7/site-packages/cohorts/cohort.pyc in _load_single_patient_merged_variants(self, patient, use_cache)
    636                                 optional_cols=[
    637                                     "t_ref_count", "t_alt_count", "n_ref_count", "n_alt_count"],
--> 638                                 encoding="latin-1"))
    639                     else:
    640                         raise ValueError("Don't know how to read %s" % patient_variants)

TypeError: ("load_maf() got an unexpected keyword argument 'encoding'", u'occurred at index 0')
```

Looks like the most recent `cohorts` version (`0.5.4`) is not compatible with python 2.7

**Comment by hammer** [comment]
Why are we trying to maintain compatibility with Python 2.7?

**Comment by jburos** [comment]
well, one reason is that this is a public tool, and we've listed it as py27 compatible. Otherwise, in our usage, we've been supporting both for some time; haven't agreed whether to break this support but it's something we've started to discuss.

**Comment by hammer** [comment]
I'd love to break support for 2.7; it's official policy for the scientific Python stack: http://www.python3statement.org.

**Comment by jburos** [comment]
This seems reasonable enough - though it's useful to separate that discussion from this issue .. 

Re: this particular issue, it looks like the `io` package provides py2/3 compatible ways to open files with encoding. 

E.g. signature for their [`open` function](https://docs.python.org/2/library/io.html#io.open):

```py
io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True)
```

**Comment by tavinathanson** [comment]
@jburos I did use `io` where needed when I last looked at these issues; but AFAICT this is complaining that `load_maf` doesn't take in `encoding`, which it does: https://github.com/hammerlab/varcode/blob/master/varcode/maf.py#L51

Maybe you're using the wrong version of Varcode? Maybe we didn't add the latest version to a requirements somewhere?

**Comment by jburos** [comment]
varcode version is `0.5.14`

**Comment by tavinathanson** [comment]
@jburos ah, you need to be on `0.5.15`; also in `requirements.txt` at https://github.com/hammerlab/cohorts/blob/master/requirements.txt#L6

**Comment by jburos** [comment]
@tavinathanson odd that `pip install -r requirements.txt` upgraded my `cohorts` install but did not upgrade its dependencies? running `pip install --upgrade cohorts` solved the problem .. but oddly didn't change the cohorts version.

**Comment by jburos** [comment]
anyways, confirming this solved the issue once `varcode` was upgraded. thanks for your help
