### ISSUE TITLE
Fix isovar git dependency

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cohorts#23]
Not sure what the right way is to specify git packages in `setup.py`, but right now `pip install .` or `python setup.py install` give me the following message.

```
Collecting isovar>=0.0.2 (from cohorts==0.1.0+6.gd3244aa)
  Could not find a version that satisfies the requirement isovar>=0.0.2 (from cohorts==0.1.0+6.gd3244aa) (from versions: )
No matching distribution found for isovar>=0.0.2 (from cohorts==0.1.0+6.gd3244aa)
```

I can work around it with running the following first

``` sh
pip install git+git://github.com/hammerlab/isovar
```

**Comment by tavinathanson** [comment]
Interesting, maybe we need to remove the `isovar>=0.0.2` dependency and leave the `dependency_links` dependency on `isovar`'s repo?
