### ISSUE TITLE
Is verify_cache still needed?

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cohorts#25]
Hitting a bug with `verify_cache`

``` python
    def verify_cache(self, cache_names):
        bad_caches = []
        for cache_name in cache_names.values():
            cache_dir = path.join(self.cache_dir, cache_name)
            if path.exists(cache_dir):
                cache_subdirs = set(listdir(cache_dir))
                cache_int_subdirs = set([int(name) for name in cache_subdirs])
                if len(cache_subdirs) != len(cache_int_subdirs):
                    bad_caches.append(cache_name)

        if len(bad_caches) > 0:
            raise ValueError("Caches %s have duplicate int/str directories" %
                             str(bad_caches))
```

```
/demeter/users/ahujaa01/src/hammerlab/cohorts/cohorts/load.pyc in verify_cache(self, cache_names)
    254             if path.exists(cache_dir):
    255                 cache_subdirs = set(listdir(cache_dir))
--> 256                 cache_int_subdirs = set([int(name) for name in cache_subdirs])
    257                 if len(cache_subdirs) != len(cache_int_subdirs):
    258                     bad_caches.append(cache_name)

ValueError: invalid literal for int() with base 10: 'TCGA-55-7907'
```

Is this still needed? Seems to assume that the sample ids are `int`s?

**Comment by tavinathanson** [comment]
Oops, yeah, it was a way for me to ensure that I didn't have `0040` and `40` in the same directory, which is particularly useful immediately post-refactor (where `40` became `"0040"`).

I didn't consider the impact to string IDs that aren't `int`-able. What if we rename to `verify_int_cache` and only do this for `int`-able IDs? Also open to removing it.

**Comment by arahuja** [comment]
> I didn't consider the impact to string IDs that aren't int-able. What if we rename to verify_int_cache and only do this for int-able IDs? Also open to removing it.

Not sure I understand - shouldn't the IDs stay as strings (with padding if necessary) the whole time?

**Comment by tavinathanson** [comment]
Sorry, I wasn't clear: they do stay as strings the whole time, and if I nuked my cache after every change this wouldn't be an issue. But I wanted to ensure that if someone hadn't nuked their cache, and ended up with `40` from before and `0040` currently, that would be caught.

**Comment by arahuja** [comment]
>  if I nuked my cache after every change this wouldn't be an issue

Is it every change or this latest to ensure they stay as strings? If so, I'd say let's remove this as it would be fine to have to recreate some caches this time.

**Comment by tavinathanson** [comment]
I agree that it would be fine to have to recreate some caches; I added this in the event that someone forgot to. (Because I did forget to and this issue created a problem for me.)

That being said, in light of having switched `sample_id` to `patient_id`, old caches should be broken anyway. So sure, let's remove this.
