### ISSUE TITLE
Travis python2.7 build failing

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cohorts#53]
```
Collecting scikit-bio>=0.4.2 (from isovar==0.0.6->-r requirements.txt (line 14))
  Downloading scikit-bio-0.5.0.zip (8.4MB)
    100% |████████████████████████████████| 8.4MB 124kB/s 
    Complete output from command python setup.py egg_info:
    scikit-bio can only be used with Python 3. You are currently running Python 2.
```

This seems to come from the newest `isovar`
1. We can (or isovar) fix this is to `0.4.21`
2. What do you think about fixing `isovar` to as this pulled a new version after a version bump yesterday.

**Comment by tavinathanson** [comment]
I think we keep going back and forth on fixing `isovar`, but still seems like more pain than gain to me? Otherwise I guess we can close this since it's addressed in https://github.com/hammerlab/isovar/pull/28?
