### ISSUE TITLE
VariantCollection metadata is lost after filtering

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cohorts#66]
Example:

```
vc = cohort.load_variants()
vc[0].metadata
{}
```

```
vc = cohort.load_variants(filter_fn=None)
vc[0].metadata
{Variant(contig='1', ...
```

**Comment by arahuja** [comment]
Good catch, looks like the metadata needs to be brought over from the older variant collection in `varcode_utils`

```
        return VariantCollection([variant
                                  for variant in variant_collection
                                  if filter_fn(variant, variant_collection.metadata[variant])
                                  ])
```

**Comment by arahuja** [comment]
We should use varcode's `clone_with_new_elements`: https://github.com/hammerlab/varcode/blob/master/varcode/collection.py#L99-L107

**Comment by tavinathanson** [comment]
Will `clone_with_new_elements` end up with extra metadata (for extra variants) that is no longer applicable? For my PR just now I manually copied over the metadata, though that seems non-ideal https://github.com/hammerlab/cohorts/pull/67/files#diff-481facac58e4fae6c10b3d93a889284eR576

**Comment by arahuja** [comment]
You fixed this correct @tavinathanson?

**Comment by tavinathanson** [comment]
Yup, fixed in https://github.com/hammerlab/varcode/issues/159
